language: node_js
node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_ca7c59bd6c80_key -iv $encrypted_ca7c59bd6c80_iv
  -in client-secret.json.enc -out client-secret.json -d

before_deploy: "../cli/create_env_file.sh"
deploy:
  provider: gae
  keyfile: "./client-secret.json"
  project: jaam-platform
  skip_cleanup: true

