language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - cd ./services
  - openssl aes-256-cbc -K $encrypted_ca7c59bd6c80_key -iv $encrypted_ca7c59bd6c80_iv -in client-secret.json.enc -out client-secret.json -d

before_deploy:
  - chmod +x ../cli/create_env_file.sh
  - ../cli/create_env_file.sh

deploy:
  provider: gae
  keyfile: client-secret.json
  project: jaam-platform
  skip_cleanup: true
